### PR TITLE
Redesign react

### PR DESCRIPTION
**Pull request by Durbin-Elijah**
Improved user aesthetics and readability by redesigning login and sign up pages.

Also redesigns top navbar, doesn't fit as well into current pages but will later fit into the general site design

Still need to do home page separately.

Any reviewer please let me know if more comments are necessary anywhere.

### CODE REVIEW

**Review by nilsstreedain — APPROVED** [review]
Looks good to me, additional iterative changes will definitely take place as we move forward but looks great on my end.

**Review by nilsstreedain — CHANGES_REQUESTED** [review]
Not sure why this didn't happen last time I reviewed but I think arrow-left-solid.svg needs to be committed. Got the following error on `npm run start`:
```
Compiled with problems:X

ERROR in ./src/styles/pages.css (./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[2]!./node_modules/source-map-loader/dist/cjs.js!./src/styles/pages.css) 5:36-97

Module not found: Error: Can't resolve '../../public/arrow-left-solid.svg' in '/Users/nilsstreedain/github/classroom-polling/client/src/styles'
```

**Comment by Durbin-Elijah** [comment]
> Not sure why this didn't happen last time I reviewed but I think arrow-left-solid.svg needs to be committed. Got the following error on `npm run start`:
> 
> ```
> Compiled with problems:X
> 
> ERROR in ./src/styles/pages.css (./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[2]!./node_modules/source-map-loader/dist/cjs.js!./src/styles/pages.css) 5:36-97
> 
> Module not found: Error: Can't resolve '../../public/arrow-left-solid.svg' in '/Users/nilsstreedain/github/classroom-polling/client/src/styles'
> ```

ah my bad, okay I added that one in.

**Review by nilsstreedain — CHANGES_REQUESTED** [review]
Now getting the following warning:
```
WARNING in ./src/styles/pages.css (./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[2]!./node_modules/source-map-loader/dist/cjs.js!./src/styles/pages.css)
Module Warning (from ./node_modules/postcss-loader/dist/cjs.js):
Warning
```
Does this need to be addressed? I haven't seen this before

**Comment by Durbin-Elijah** [comment]
> Now getting the following warning:
> 
> ```
> WARNING in ./src/styles/pages.css (./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[2]!./node_modules/source-map-loader/dist/cjs.js!./src/styles/pages.css)
> Module Warning (from ./node_modules/postcss-loader/dist/cjs.js):
> Warning
> ```
> 
> Does this need to be addressed? I haven't seen this before

I think this is unrelated, it seems to happen in dev branch as well @nilsstreedain

**Comment by nilsstreedain** [comment]
> > Now getting the following warning:
> > ```
> > WARNING in ./src/styles/pages.css (./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[2]!./node_modules/source-map-loader/dist/cjs.js!./src/styles/pages.css)
> > Module Warning (from ./node_modules/postcss-loader/dist/cjs.js):
> > Warning
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Does this need to be addressed? I haven't seen this before
> 
> I think this is unrelated, it seems to happen in dev branch as well @nilsstreedain

Shoot I think I just previously had errors muted unknowningly

**Review by nilsstreedain — APPROVED** [review]

**Pull request merged**
